### PR TITLE
Update mimilove.c

### PR DESCRIPTION
**Pull request by febriyantonugroho**

### CODE REVIEW

**Comment by gentilkiwi** [comment]
Really ?

**Comment by t0b1nux** [comment]
Wow ! This PR is a troll, isn't it ?

**Comment by AndrewSav** [comment]
@t0b1nux so someone wanted to help with formatting and style, what's wrong with that? =)

**Comment by t0b1nux** [comment]
I don't know. Maybe adding inconsistent style in source code shall be considered a good practice ? no idea :-D

**Pull request closed without merging**
